apiVersion: v2
name: ricochet-helm
description: A Helm chart for deploying Ricochet server
type: application
version: 0.3.0
appVersion: 0.1.1
icon: https://ricochet.rs/logo.png
keywords:
  - ricochet
  - rust
  - server
  - data science
sources:
  - https://github.com/ricochet
maintainers:
  - name: Ricochet Team
    email: contact@ricochet.rs
