{{- if and .Values.apps.deployment.persistence.cache.enabled (not .Values.apps.deployment.persistence.cache.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ricochet.fullname" . }}-apps-cache
  labels:
    {{- include "ricochet.labels" . | nindent 4 }}
  {{- with .Values.apps.deployment.persistence.cache.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.apps.deployment.persistence.cache.accessMode }}
  {{- if .Values.apps.deployment.persistence.cache.storageClass }}
  {{- if eq .Values.apps.deployment.persistence.cache.storageClass "-" }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.apps.deployment.persistence.cache.storageClass | quote }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.apps.deployment.persistence.cache.size }}
{{- end }}
